import{a as S,S as v,i as a}from"./assets/vendor-Bt_EzQve.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&r(p)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const M="https://pixabay.com/api/",P="52982247-0d25e92a2d7c3074b601ee372",g=15,h=g;async function y(o,e=1){return(await S.get(M,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:g}})).data}const n={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")},E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function L(o,e=!1){const i=o.map(r=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${r.largeImageURL}">
          <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b><p class="info-item-result">${r.likes}</p></p>
          <p class="info-item"><b>Views:</b><p class="info-item-result">${r.views}</p></p>
          <p class="info-item"><b>Comments:</b><p class="info-item-result">${r.comments}</p></p>
          <p class="info-item"><b>Downloads:</b><p class="info-item-result">${r.downloads}</p></p>
        </div>
      </li>`).join("");e?n.gallery.insertAdjacentHTML("beforeend",i):n.gallery.innerHTML=i,E.refresh()}function R(){n.gallery.innerHTML=""}function b(){n.loader.classList.remove("hidden")}function u(){n.loader.classList.add("hidden")}function w(){n.loadMoreBtn.classList.remove("is-hidden")}function l(){n.loadMoreBtn.classList.add("is-hidden")}const f={form:document.querySelector(".form"),input:document.querySelector('input[name="search-text"]'),loadMoreBtn:document.querySelector(".load-more-btn")};let d="",c=1,m=0;f.form.addEventListener("submit",q);f.loadMoreBtn.addEventListener("click",B);async function q(o){if(o.preventDefault(),d=f.input.value.trim(),!d){a.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}c=1,R(),f.input.value="",l();try{b();const e=await y(d,c);if(u(),!e.hits||e.hits.length===0){a.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m=e.totalHits,L(e.hits),Math.ceil(m/h)>1?w():(l(),a.info({message:"That's all results for your search!",position:"topRight"}))}catch(e){u(),console.error(e),a.error({title:"Error",message:"Something went wrong while fetching images.",position:"topRight"})}}async function B(){c+=1,l(),b();try{const o=await y(d,c);if(u(),!o.hits||o.hits.length===0){a.info({message:"No more images to load.",position:"topRight"}),l();return}L(o.hits,!0);const e=Math.ceil(m/h);c>=e?(l(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w();const i=document.querySelector(".gallery");if(i&&i.firstElementChild){const{height:r}=i.firstElementChild.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}}catch(o){u(),console.error(o),a.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}}
//# sourceMappingURL=index.js.map
