import{a as b,S as w,i as u}from"./assets/vendor-Bt_EzQve.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const d of o.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&s(d)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const v="https://pixabay.com/api/",M="52982247-0d25e92a2d7c3074b601ee372",p=15,S=p;async function m(r,t=1){return(await b.get(v,{params:{key:M,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:p}})).data}const n={gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMoreBtn:document.querySelector(".load-more-btn")},q=new w(".gallery a",{captionsData:"alt",captionDelay:250});function y(r,t=!1){const a=r.map(s=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${s.largeImageURL}">
          <img class="gallery-image" src="${s.webformatURL}" alt="${s.tags}" loading="lazy"/>
        </a>
        <div class="info">
          <p class="info-item"><b>Likes:</b><p class="info-item-result">${s.likes}</p></p>
          <p class="info-item"><b>Views:</b><p class="info-item-result">${s.views}</p></p>
          <p class="info-item"><b>Comments:</b><p class="info-item-result">${s.comments}</p></p>
          <p class="info-item"><b>Downloads:</b><p class="info-item-result">${s.downloads}</p></p>
        </div>
      </li>`).join("");t?n.gallery.insertAdjacentHTML("beforeend",a):n.gallery.innerHTML=a,q.refresh()}function P(){n.gallery.innerHTML=""}function h(){n.loader.classList.remove("hidden")}function f(){n.loader.classList.add("hidden")}function B(){n.loadMoreBtn.classList.remove("is-hidden")}function g(){n.loadMoreBtn.classList.add("is-hidden")}const c={form:document.querySelector(".form"),input:document.querySelector('input[name="search-text"]'),loadMoreBtn:document.querySelector(".load-more-btn")};let l="",i=1,L=0;c.form.addEventListener("submit",E);c.loadMoreBtn.addEventListener("click",R);async function E(r){if(r.preventDefault(),l=c.input.value.trim(),!l){u.warning({title:"Warning",message:"Please enter a search query",position:"topRight"});return}i=1,P(),c.input.value="",g(),h();const t=await m(l,i);if(f(),!t.hits||t.hits.length===0){u.error({title:"",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L=t.totalHits,y(t.hits),B()}async function R(){i+=1,h();try{const r=await m(l,i);f(),y(r.hits,!0);const t=Math.ceil(L/S);i>=t&&(g(),u.info({title:"",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const{height:a}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}catch(r){f(),console.error(r)}}
//# sourceMappingURL=index.js.map
